### ISSUE TITLE
Android Pie Issue

### ISSUE THREAD

**Issue by benskarunya** [derek82511/cordova-azure-notification-hubs#8]
@derek82511 

I am getting below issue after updated to 1.0.6 with cordova android@8.0.0. Please need help!

E/AndroidRuntime: FATAL EXCEPTION: pool-14-thread-2
    Process: xxxx, PID: 29188
    java.lang.NoClassDefFoundError: Failed resolution of: [Lorg/apache/http/Header;
        at com.microsoft.windowsazure.messaging.NotificationHub.refreshRegistrationInformation(NotificationHub.java:296)
        at com.microsoft.windowsazure.messaging.NotificationHub.registerInternal(NotificationHub.java:390)
        at com.microsoft.windowsazure.messaging.NotificationHub.register(NotificationHub.java:143)
        at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:216)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.Header" on path: DexPathList[[zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/base.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_dependencies_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_resources_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_0_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_1_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_2_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_3_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_4_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_5_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_6_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_7_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_8_apk.apk", zip file "/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.microsoft.windowsazure.messaging.NotificationHub.refreshRegistrationInformation(NotificationHub.java:296) 
        at com.microsoft.windowsazure.messaging.NotificationHub.registerInternal(NotificationHub.java:390) 
        at com.microsoft.windowsazure.messaging.NotificationHub.register(NotificationHub.java:143) 
        at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:216) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/xxxx-GplJV9zj3b-p5EEpKDrq2g==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:764)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:847)
        at android.app.LoadedApk.getResources(LoadedApk.java:1088)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6095)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by benskarunya** [comment]
I have fixed this issue by adding below line in the AndroidMainfest.xml file,

App crashed due to ‘Apache HTTP client deprecation’. Beginning with Android 9, that library is removed from the bootclasspath and is not available to apps by default.

To continue using the Apache HTTP client, apps that target Android 9 and above can add the following to their AndroidManifest.xml:

<uses-library android:name="org.apache.http.legacy" android:required="false"/>

https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p

**Comment by derek82511** [comment]
@benskarunya Thanks for your help!
